require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PixelPicsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # PixelPic. As you add validations to PixelPic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PixelPicsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pixel_pics as @pixel_pics" do
      pixel_pic = PixelPic.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:pixel_pics)).to eq([pixel_pic])
    end
  end

  describe "GET show" do
    it "assigns the requested pixel_pic as @pixel_pic" do
      pixel_pic = PixelPic.create! valid_attributes
      get :show, {:id => pixel_pic.to_param}, valid_session
      expect(assigns(:pixel_pic)).to eq(pixel_pic)
    end
  end

  describe "GET new" do
    it "assigns a new pixel_pic as @pixel_pic" do
      get :new, {}, valid_session
      expect(assigns(:pixel_pic)).to be_a_new(PixelPic)
    end
  end

  describe "GET edit" do
    it "assigns the requested pixel_pic as @pixel_pic" do
      pixel_pic = PixelPic.create! valid_attributes
      get :edit, {:id => pixel_pic.to_param}, valid_session
      expect(assigns(:pixel_pic)).to eq(pixel_pic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PixelPic" do
        expect {
          post :create, {:pixel_pic => valid_attributes}, valid_session
        }.to change(PixelPic, :count).by(1)
      end

      it "assigns a newly created pixel_pic as @pixel_pic" do
        post :create, {:pixel_pic => valid_attributes}, valid_session
        expect(assigns(:pixel_pic)).to be_a(PixelPic)
        expect(assigns(:pixel_pic)).to be_persisted
      end

      it "redirects to the created pixel_pic" do
        post :create, {:pixel_pic => valid_attributes}, valid_session
        expect(response).to redirect_to(PixelPic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pixel_pic as @pixel_pic" do
        post :create, {:pixel_pic => invalid_attributes}, valid_session
        expect(assigns(:pixel_pic)).to be_a_new(PixelPic)
      end

      it "re-renders the 'new' template" do
        post :create, {:pixel_pic => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pixel_pic" do
        pixel_pic = PixelPic.create! valid_attributes
        put :update, {:id => pixel_pic.to_param, :pixel_pic => new_attributes}, valid_session
        pixel_pic.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested pixel_pic as @pixel_pic" do
        pixel_pic = PixelPic.create! valid_attributes
        put :update, {:id => pixel_pic.to_param, :pixel_pic => valid_attributes}, valid_session
        expect(assigns(:pixel_pic)).to eq(pixel_pic)
      end

      it "redirects to the pixel_pic" do
        pixel_pic = PixelPic.create! valid_attributes
        put :update, {:id => pixel_pic.to_param, :pixel_pic => valid_attributes}, valid_session
        expect(response).to redirect_to(pixel_pic)
      end
    end

    describe "with invalid params" do
      it "assigns the pixel_pic as @pixel_pic" do
        pixel_pic = PixelPic.create! valid_attributes
        put :update, {:id => pixel_pic.to_param, :pixel_pic => invalid_attributes}, valid_session
        expect(assigns(:pixel_pic)).to eq(pixel_pic)
      end

      it "re-renders the 'edit' template" do
        pixel_pic = PixelPic.create! valid_attributes
        put :update, {:id => pixel_pic.to_param, :pixel_pic => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pixel_pic" do
      pixel_pic = PixelPic.create! valid_attributes
      expect {
        delete :destroy, {:id => pixel_pic.to_param}, valid_session
      }.to change(PixelPic, :count).by(-1)
    end

    it "redirects to the pixel_pics list" do
      pixel_pic = PixelPic.create! valid_attributes
      delete :destroy, {:id => pixel_pic.to_param}, valid_session
      expect(response).to redirect_to(pixel_pics_url)
    end
  end

end
